from .TokenPairView import TokenPairView
from .ProduitViewset import ProduitViewset
from .ServeurViewset import ServeurViewset
from .ClientViewset import ClientViewset
from .TableViewset import TableViewset
from .AchatViewset import AchatViewset
from .SortieViewset import SortieViewset
from .DetailCommandeViewset import DetailCommandeViewset
from .PaiementViewset import PaiementViewset
from .RecetteViewset import RecetteViewset
from .CommandeViewset import CommandeViewset
from .StatisticViewset import StatisticViewset
